services:
  app:
    build: .
    ports:
      - "3005:3002"
    env_file:
      - .env
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: